root = "."
tmp_dir = ".air_tmp"

[build]
  cmd = "go build -buildvcs=false -o .air_tmp/main ./cmd/server"
  bin = ".air_tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", ".air_tmp"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[run]
  cmd = ".air_tmp/main"
