# air.toml  (or .air.toml, but match your command)
root    = "."
tmp_dir = ".air_tmp"

[build]
  cmd      = "go build -o .air_tmp/main ./cmd/server"
  bin      = ".air_tmp/main"
  full_bin = true     # <- boolean, no quotes

[log]
  main_only = false   # <- boolean, no quotes
  time      = true    # <- boolean, no quotes

[include]
  directories = ["internal","cmd"]
  extensions  = ["go","tpl","tmpl","html"]

[exclude]
  directories = ["vendor",".air_tmp"]
