services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app/cmd/server
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    command: air
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: infinite
      POSTGRES_USER: ieuser
      POSTGRES_PASSWORD: iepass
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sanketpandia@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ieadmin
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  pgdata-dev:
