version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./config:/app/config
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: infinite
      POSTGRES_USER: ieuser
      POSTGRES_PASSWORD: iepass
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-prod:
