version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    command: air
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: infinite
      POSTGRES_USER: ieuser
      POSTGRES_PASSWORD: iepass
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata-dev:
