basePath: /
definitions:
  dtos.APIResponse:
    properties:
      data: {}
      message:
        type: string
      response_time:
        type: string
      status:
        type: string
    type: object
  dtos.InitUserRegistrationReq:
    properties:
      ifc_id:
        type: string
      last_flight:
        type: string
    type: object
  dtos.UserRegisterSwaggerResponse:
    properties:
      data:
        $ref: '#/definitions/responses.UserRegisterResponse'
      error:
        type: string
      status:
        type: string
      timestamp:
        type: string
    type: object
  requests.RegisterUserRequest:
    properties:
      discord_id:
        type: string
      if_community_id:
        type: string
      server_id:
        type: string
    required:
    - discord_id
    - if_community_id
    - server_id
    type: object
  responses.UserRegisterResponse:
    properties:
      error:
        type: string
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: sanket@example.com
    name: Sanket Pandia
  description: Backend for Infinite Experiment bot and web client.
  title: Infinite Experiment API
  version: "1.0"
paths:
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with Discord ID and IF Community username.
      parameters:
      - description: User Registration Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserRegisterSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.UserRegisterSwaggerResponse'
      summary: Register a new user
      tags:
      - Users
  /api/v1/user/register/init:
    post:
      consumes:
      - application/json
      description: Initiates the user registration process given an IF Community ID
        (IFC ID).
      parameters:
      - description: Discord ID
        in: header
        name: X-Discord-Id
        required: true
        type: string
      - default: "123456789"
        description: Discord Server ID
        in: header
        name: X-Server-Id
        required: true
        type: string
      - description: API KEY
        in: header
        name: X-API-Key
        required: true
        type: string
      - description: IFC ID Payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.InitUserRegistrationReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Initiate user registration
      tags:
      - Users
  /api/v1/users/delete:
    get:
      description: Deletes all users in the database. Intended for development/testing
        only.
      parameters:
      - default: "668664447950127154"
        description: Discord ID
        in: header
        name: X-Discord-Id
        required: true
        type: string
      - default: "988020008665882624"
        description: Discord Server ID
        in: header
        name: X-Server-Id
        required: true
        type: string
      - default: API_KEY_123
        description: API KEY
        in: header
        name: X-API-Key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Always returns error; not implemented for production use
          schema:
            $ref: '#/definitions/dtos.APIResponse'
      summary: Delete all users (Test Only)
      tags:
      - Test
  /healthCheck:
    get:
      description: Verifies the server is running.
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health check
      tags:
      - Misc
swagger: "2.0"
